// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_place_100_towers = "CgkIu_u8pJMOEAIQBA"; // <GPGSID>
        public const string achievement_place_10_towers = "CgkIu_u8pJMOEAIQAw"; // <GPGSID>
        public const string leaderboard_most_enemies_killed = "CgkIu_u8pJMOEAIQBg"; // <GPGSID>
        public const string achievement_kill_20_enemies = "CgkIu_u8pJMOEAIQAg"; // <GPGSID>
        public const string achievement_kill_10_enemies = "CgkIu_u8pJMOEAIQAQ"; // <GPGSID>
        public const string achievement_test_achievement = "CgkIu_u8pJMOEAIQBQ"; // <GPGSID>

}

